server:
  shutdown: graceful

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:

  datasource:
    driver-class-name: ${DB_CLASS_NAME}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: ${DB_PLATFORM}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

encrypt:
  secret-key: ${ENCRYPT_SECRET_KEY}